[package]
name = "ferris"
version = "0.0.0"
description = "A Tauri App"
authors = ["TENDOUZHI"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.1", features = ["api-all"] }
windows = {version = "0.42.0"}
image = "0.24.4"
image-base64 = "0.1.0"
zip = "0.6.2"
walkdir = "2.3.2"
rfd = "0.10.0"
webbrowser = "0.8.1"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
